import React from 'react';
import { Box, Typography, Link, Container, Divider, List, ListItem, ListItemText } from '@mui/material';

const Cookies: React.FC = () => {
  return (
    <Container maxWidth="md" sx={{ py: { xs: 4, md: 6 }, color: '#1b1c3a' }}>
      <Typography variant="h3" gutterBottom sx={{ fontWeight: 'bold', mb: 2 }}>
        Cookie Policy
      </Typography>

      <Typography variant="subtitle2" color="text.secondary" gutterBottom>
        Effective Date: 18-July-2025<br />
        Last Updated: 18-July-2025
      </Typography>

      <Divider sx={{ my: 3 }} />

      <Typography variant="h5" gutterBottom>
        What are cookies?
      </Typography>
      <Typography paragraph>
        Cookies are small text files stored on your device when the website is loaded. They help us make the website
        function properly, enhance security, improve user experience, and understand what works and what needs improvement.
      </Typography>

      <Typography variant="h5" gutterBottom>
        How do we use cookies?
      </Typography>
      <Typography paragraph>
        Our website uses first-party and third-party cookies. First-party cookies are essential for proper functionality.
        Third-party cookies help us understand website performance, user interaction, and display relevant content.
      </Typography>

      <Typography variant="h5" gutterBottom>
        Manage cookie preferences
      </Typography>
      <Typography paragraph>
        You can manage or withdraw your cookie consent anytime by visiting the cookie settings.
        Most browsers also allow you to delete or block cookies. Here are some useful links:
      </Typography>

      <List dense>
        {[
          {
            label: 'Chrome',
            href: 'https://support.google.com/accounts/answer/32050',
          },
          {
            label: 'Safari',
            href: 'https://support.apple.com/en-in/guide/safari/sfri11471/mac',
          },
          {
            label: 'Firefox',
            href: 'https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox',
          },
          {
            label: 'Internet Explorer',
            href: 'https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc',
          },
        ].map(({ label, href }) => (
          <ListItem key={label} disableGutters>
            <ListItemText
              primary={
                <Link href={href} target="_blank" rel="noopener" underline="hover" color="primary">
                  {label}
                </Link>
              }
            />
          </ListItem>
        ))}
      </List>

      <Box mt={4}>
        <Typography variant="caption" color="text.secondary">
          Cookie Policy generated by CookieYes | Customized by Cedmo MFF
        </Typography>
      </Box>
    </Container>
  );
};

export default Cookies;
